OGRE: Ogre::RTShader::AssignmentAtom Class Reference
Ogre::RTShader::AssignmentAtom Class Reference
Optional Components » RTShaderSystem
shorthand for "lhs = rhs;" insted of using FFP_Assign(rhs, lhs)
#include <OgreShaderFunctionAtom.h>
Public Types
typedef vector< Operand >::type OperandVector
Public Member Functions
AssignmentAtom (int groupOrder)
AssignmentAtom (ParameterPtr lhs, ParameterPtr rhs, int groupOrder)
const String & getFunctionAtomType ()
const String & getFunctionName () const
Return the function name.
int getGroupExecutionOrder () const
Get the group execution order of this function atom.
int getInternalExecutionOrder () const
Get an internal execution order within a group of this function atom.
OperandVector & getOperandList ()
Get a list of parameters this function invocation will use in the function call as arguments.
const String & getReturnType () const
Return the return type.
bool operator!= (const FunctionInvocation &rhs) const
Determines if the current object is not equal to the compared one.
bool operator< (const FunctionInvocation &rhs) const
Determines if the current object is less than the compared one.
bool operator== (const FunctionInvocation &rhs) const
Determines if the current object is equal to the compared one.
void pushOperand (ParameterPtr parameter, Operand::OpSemantic opSemantic, int opMask=Operand::OPM_ALL, int indirectionLevel=0)
Push a new operand (on the end) to the function.
void writeSourceCode (std::ostream &os, const String &targetLanguage) const
Static Public Attributes
static String Type
Detailed Description
shorthand for "lhs = rhs;" insted of using FFP_Assign(rhs, lhs)
Member Typedef Documentation
typedef vector<Operand>::type Ogre::RTShader::FunctionInvocation::OperandVector inherited
Constructor & Destructor Documentation
Ogre::RTShader::AssignmentAtom::AssignmentAtom (int groupOrder) inline explicit
Ogre::RTShader::AssignmentAtom::AssignmentAtom (ParameterPtr lhs, ParameterPtr rhs, int groupOrder)
Member Function Documentation
void Ogre::RTShader::AssignmentAtom::writeSourceCode (std::ostream & os, const String & targetLanguage) const virtual
See also
FunctionAtom::writeSourceCode
Reimplemented from Ogre::RTShader::FunctionInvocation.
const String& Ogre::RTShader::AssignmentAtom::getFunctionAtomType () inline virtual
See also
FunctionAtom::getFunctionAtomType
Reimplemented from Ogre::RTShader::FunctionInvocation.
OperandVector& Ogre::RTShader::FunctionInvocation::getOperandList () inline inherited
Get a list of parameters this function invocation will use in the function call as arguments.
References Ogre::RTShader::Operand::OPM_ALL.
void Ogre::RTShader::FunctionInvocation::pushOperand (ParameterPtr parameter, Operand::OpSemantic opSemantic, int opMask = Operand::OPM_ALL, int indirectionLevel = 0) inherited
Push a new operand (on the end) to the function.
Parameters
parameter A function parameter.
opSemantic The in/out semantic of the parameter.
opMask The field mask of the parameter.
indirectionLevel The level of nesting inside brackets
const String& Ogre::RTShader::FunctionInvocation::getFunctionName () const inline inherited
Return the function name.
const String& Ogre::RTShader::FunctionInvocation::getReturnType () const inline inherited
Return the return type.
References Ogre::operator!=(), Ogre::operator<(), and Ogre::operator==().
bool Ogre::RTShader::FunctionInvocation::operator== (const FunctionInvocation & rhs) const inherited
Determines if the current object is equal to the compared one.
bool Ogre::RTShader::FunctionInvocation::operator!= (const FunctionInvocation & rhs) const inherited
Determines if the current object is not equal to the compared one.
bool Ogre::RTShader::FunctionInvocation::operator< (const FunctionInvocation & rhs) const inherited
Determines if the current object is less than the compared one.
int Ogre::RTShader::FunctionAtom::getGroupExecutionOrder () const inherited
Get the group execution order of this function atom.
int Ogre::RTShader::FunctionAtom::getInternalExecutionOrder () const inline inherited
Get an internal execution order within a group of this function atom.
Member Data Documentation
String Ogre::RTShader::AssignmentAtom::Type static
The documentation for this class was generated from the following file:
OgreShaderFunctionAtom.h